spring:
  datasource:
    url: jdbc:h2:mem:testdb
    tomcat:
      default-auto-commit: false
      max-active: 10
      max-idle: 10
      initial-size: 5
      max-wait: 3000
      test-on-borrow: true
      jmx-enabled: false
  #    username: sa
#    password: 123
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  jackson:
    default-property-inclusion: non_null      # com.fasterxml.jackson.annotation.JsonInclude.Include
    deserialization:                          # com.fasterxml.jackson.databind.DeserializationFeature
      FAIL_ON_UNKNOWN_PROPERTIES : false
  messages:
    basename: ValidationMessages
    encoding: utf-8
server:
  port: 8080

security:
  allow-credentials: true
  allowed-origins:
    - http://localhost:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - Cache-Control
    - Id-Token
  allowed-public-apis:
    - /public/**
  exposed-headers:
    - X-Xsrf-Token