spring:
  datasource:
    url: jdbc:h2:mem:testdb
#    username: sa
#    password: 123
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  jackson:
#    date-format: yyyy/MM/dd
    default-property-inclusion: non_null      # com.fasterxml.jackson.annotation.JsonInclude.Include
    deserialization:                          # com.fasterxml.jackson.databind.DeserializationFeature
      FAIL_ON_UNKNOWN_PROPERTIES : false
server:
  port: 8080